var oncCenter = {
    name: "onc_center_KsHJ",
    path: "nemesis/images/ONC_center_KsHJ.jpeg",
    fov: 0.1667,
    corners: [83.90667776, -5.47253760, 83.73906731, -5.47224789, 83.73949401, -5.30549402, 83.90704103, -5.30577480],
    toggleBgr: true,
    details: [],
    info: "The center of the Orion Nebula Cluster is extremely bright, but we can adjust the image so that we can see what is happening in the densely populated central region. We find a large number of very young stars that have just recently been born."
};
var oncOverview = {
    name: "onc_overview_KsHJ",
    path: "nemesis/images/ONC_overview_KsHJ-scaled.jpeg",
    fov: 1,
    corners: [84.23588395, -6.00718484, 83.22774838, -6.00543309, 83.23035607, -5.00283380, 84.23679279, -5.00458253],
    toggleBgr: true,
    details: [oncCenter],
    info: "This near infrared color composite shows the Orion Nebula Cluster (ONC). This star-forming region is host to many young stars which illuminate and ionize the surrounding gas. As a result, the Orion Nebula is a most prominent star-forming region, even visible to the naked eye."
};
var hops150 = {
    name: "hops_150_KsHJ",
    path: "nemesis/images/hops_150_KsHJ.jpeg",
    fov: 0.25,
    corners: [84.86761945, -7.36673453, 84.36306247, -7.36644799, 84.36363455, -6.86608603, 84.86761131, -6.86634743],
    toggleBgr: false,
    details: [],
    info: "This young stellar object, HOPS 150 (number 150 in the Herschel Orion Protostar Survey), is a specially interesting source. HOPS 150 is still in an early evolutionary stage, and is still embedded in its protostellar envelope. Yet, an accretion disk has already formed, and the central object is actively accreting material. As a consequence, some of the infalling material is accelerated away from the central object along the polar axis forming protostellar jets, which excavate the surrounding envelope, creating outflow cavities. When the ejected material collides with the interstellar medium, it is excited and emits light (shown in red)."
};
var ngc1333 = {
    name: "ngc1333_i4i2i1",
    path: "nemesis/images/NGC1333_i4i2i1.jpeg",
    fov: 0.25,
    corners: [52.36536627, +31.18335862, 52.17033786, +31.18054834, 52.16685285, +31.34744957, 52.36221868, +31.35028453],
    toggleBgr: false,
    details: [],
    info: "NGC 1333, also known as the embryo nebula, is a reflection nebula in the Perseus molecular cloud. This turbulent region of space is densely populated by young stellar objects, many featuring prominent jets and outflows."
};
var peremb40 = {
    name: "peremb40_i4i2i1",
    path: "nemesis/images/peremb40_img_i4i2i1_lessback.jpeg",
    fov: 0.5,
    corners: [53.61342538, +30.88303918, 53.03049049, +30.87939432, 53.02461326, +31.37969065, 53.61064869, +31.38340840],
    toggleBgr: false,
    details: [],
    info: "Barnard 1, one of the dark clouds in the Perseus star-forming region is home to another young stellar object Per-emb 40. It is part of a small cluster of young stellar objects. Just north of Per-emb 40 lies Per-emb 29, which features a prominent oscillating protostellar jet."
};